In [1]:
import pandas as pd
import numpy as np

In [10]:
labels = [
    [100, '0.0'],
    [101, '0.0'],
    [102, '0.0'],
    [103, '0.0'],
    [104, '0.0'],
    [105, '0.0'],
    [106, '0.0'],
    [107, '0.0'],
    [108, '0.0'],
    [109, '0.0'],
    [200, '1.0'],
    [201, '1.0'],
    [202, '1.0'],
    [203, '1.0'],
    [204, '1.0'],
    [205, '1.0'],
    [206, '1.0'],
    [207, '1.0'],
    [208, '1.0'],
    [209, '1.0']
]

# columns
columns = ['id', 'genus']

df = pd.DataFrame(labels, columns=columns)

TypeError: Index(...) must be called with a collection of some kind, 'id' was passed

In [7]:
df.to_csv('labels.csv')

In [8]:
pd.read_csv('labels.csv')

    Unnamed: 0   id  genus
0            0  100    0.0
1            1  101    0.0
2            2  102    0.0
3            3  103    0.0
4            4  104    0.0
5            5  105    0.0
6            6  106    0.0
7            7  107    0.0
8            8  108    0.0
9            9  109    0.0
10          10  200    1.0
11          11  201    1.0
12          12  202    1.0
13          13  203    1.0
14          14  204    1.0
15          15  205    1.0
16          16  206    1.0
17          17  207    1.0
18          18  208    1.0
19          19  209    1.0